=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::AccountValidationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountValidationApi' do
  before do
    # run before each test
    @instance = BitPesa::AccountValidationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountValidationApi' do
    it 'should create an instance of AccountValidationApi' do
      expect(@instance).to be_instance_of(BitPesa::AccountValidationApi)
    end
  end

  # unit tests for post_account_validations
  # Validates the existence of a bank account
  # Validates the existence of a bank account and returns the associated customer name
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'post_account_validations test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
