=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::AccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @instance = BitPesa::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@instance).to be_instance_of(BitPesa::AccountsApi)
    end
  end

  # unit tests for get_account
  # Fetches account balance for specified currrency
  # Fetches account balance for specified currrency, and returns current balance and associated currency code
  # @param currency Currency code of account balance to fetch  Example: &#x60;/v1/accounts/USD&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'get_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_accounts
  # Fetches account balances for all currrencies
  # Fetches account balances for all currrencies, and returns an array of the current balances and associated currency codes.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_accounts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
