=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::APILogsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'APILogsApi' do
  before do
    # run before each test
    @instance = BitPesa::APILogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of APILogsApi' do
    it 'should create an instance of APILogsApi' do
      expect(@instance).to be_instance_of(BitPesa::APILogsApi)
    end
  end

  # unit tests for get_api_log
  # Fetch an individual API log
  # Returns a single API log based on the API log ID.
  # @param api_log_id ID of the API log to retrieve  Example: &#x60;/v1/api_logs/00485ce9-532b-45e7-8518-7e5582242407&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2004]
  describe 'get_api_log test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_api_logs
  # Fetch a list of API logs
  # Returns a list of API logs. Also includes information relating to the original request.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2003]
  describe 'get_api_logs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
