=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::LogsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LogsApi' do
  before do
    # run before each test
    @instance = BitPesa::LogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogsApi' do
    it 'should create an instance of LogsApi' do
      expect(@instance).to be_instance_of(BitPesa::LogsApi)
    end
  end

  # unit tests for get_webhook_log
  # Fetch an individual webhook log
  # Returns a single webhook log based on the webhook log ID.
  # @param webhook_log_id ID of the webhook log to retrieve  Example: &#x60;/v1/logs/9d1ad631-f34a-4cff-9a7e-2c83e3a556df&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20010]
  describe 'get_webhook_log test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhook_logs
  # Fetch a list of webhook logs
  # Returns a list of webhook logs. Response includes pagination.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2009]
  describe 'get_webhook_logs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
