=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::PaymentMethodsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentMethodsApi' do
  before do
    # run before each test
    @instance = BitPesa::PaymentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'should create an instance of PaymentMethodsApi' do
      expect(@instance).to be_instance_of(BitPesa::PaymentMethodsApi)
    end
  end

  # unit tests for payment_methods_in
  # This method returns possible payin methods.
  # Fetching possible payin methods. 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2008]
  describe 'payment_methods_in test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_out
  # This method returns possible payout methods.
  # Fetching possible payout methods. 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2008]
  describe 'payment_methods_out test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
