=begin
#BitPesa API

#Reference documentation for the BitPesa API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'

# Unit tests for Bitpesa::PaymentMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentMethodsApi' do
  before do
    # run before each test
    @instance = Bitpesa::PaymentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'should create an instance of PaymentMethodsApi' do
      expect(@instance).to be_instance_of(Bitpesa::PaymentMethodsApi)
    end
  end

  # unit tests for payment_methods_in
  # This method returns possible payin methods.
  # Fetching possible payin methods. 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodListResponse]
  describe 'payment_methods_in test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_methods_out
  # This method returns possible payout methods.
  # Fetching possible payout methods. 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodListResponse]
  describe 'payment_methods_out test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
