=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::PayoutMethodsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PayoutMethodsApi' do
  before do
    # run before each test
    @instance = BitPesa::PayoutMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayoutMethodsApi' do
    it 'should create an instance of PayoutMethodsApi' do
      expect(@instance).to be_instance_of(BitPesa::PayoutMethodsApi)
    end
  end

  # unit tests for get_payout_method
  # Fetching a payout method
  # Show a payout method by id
  # @param payout_method_id ID of the payout method to get.  Example: &#x60;/v1/payout_methods/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20012]
  describe 'get_payout_method test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payout_methods
  # Listing payout methods
  # List available payout methods
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20011]
  describe 'get_payout_methods test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
