=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::RecipientsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RecipientsApi' do
  before do
    # run before each test
    @instance = BitPesa::RecipientsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecipientsApi' do
    it 'should create an instance of RecipientsApi' do
      expect(@instance).to be_instance_of(BitPesa::RecipientsApi)
    end
  end

  # unit tests for delete_recipient
  # Cancelling a recipient
  # Cancels the recipient specified in the URL path.
  # @param recipient_id ID of recipient to cancel.  Example: &#x60;/v1/recipients/9d4d7b73-a94c-4979-ab57-09074fd55d33&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20014]
  describe 'delete_recipient test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_recipients
  # Getting a list of recipients with filtering
  # Fetches details of all recipients.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :state Allows filtering results by &#x60;state&#x60; of recipient. See [API Documentation - Recipient state](https://github.com/bitpesa/api-documentation/blob/master/transaction-flow.md#state-1) for possible states.  Example: &#x60;/v1/recipients?state[]&#x3D;error&amp;state[]&#x3D;initial&#x60;
  # @option opts [Array<String>] :currency Allows filtering results by &#x60;input_currency&#x60;.  Example: &#x60;/v1/recipients?currency[]&#x3D;KES&amp;currency[]&#x3D;NGN&#x60;
  # @option opts [String] :created_at Allows filtering results by the specified &#x60;created_at&#x60; timeframe.  Example: &#x60;/v1/recipients?created_at_from&#x3D;2018-06-06&amp;created_at_to&#x3D;2018-06-08&#x60;
  # @option opts [String] :amount Allows filtering results by the specified &#x60;amount&#x60; range. When using this filter, the &#x60;currency&#x60; should also be specified.  Example: &#x60;/v1/recipients?currency&#x3D;BTC&amp;amount_from&#x3D;83.76672339&amp;amount_to&#x3D;83.76672339&#x60;
  # @return [InlineResponse20013]
  describe 'get_recipients test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_recipient
  # Updating a recipient
  # Updates the recipient specified in the URL path.
  # @param recipient_id ID of recipient to update.  Example: &#x60;/v1/recipients/9d4d7b73-a94c-4979-ab57-09074fd55d33&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20014]
  describe 'patch_recipient test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
