=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BitPesa::TransactionRequestsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionRequestsApi' do
  before do
    # run before each test
    @instance = BitPesa::TransactionRequestsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionRequestsApi' do
    it 'should create an instance of TransactionRequestsApi' do
      expect(@instance).to be_instance_of(BitPesa::TransactionRequestsApi)
    end
  end

  # unit tests for get_transaction_request
  # Fetching a transaction request
  # Returns a single transaction request by the Transaction Request ID
  # @param transaction_request_id ID of the transaction request to get.  Example: &#x60;/v1/transaction_requests/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2013]
  describe 'get_transaction_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transaction_requests
  # Listing transaction requests
  # Get a list of transaction requests
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :state Returns transaction requests with specified states.  Example: &#x60;/v1/transaction_requests?state[]&#x3D;pending&amp;state[]&#x3D;modified&#x60;
  # @option opts [Array<String>] :currency Returns transaction requests with specified input_currency.  Example: &#x60;/v1/transaction_requests?state[]&#x3D;pending&amp;state[]&#x3D;modified&#x60;
  # @option opts [String] :created_at_from Returns transaction requests with specified created_at lower limit.  Example: &#x60;/v1/transaction_requests?created_at_from&#x3D;2018-06-09&#x60;
  # @option opts [String] :created_at_to Returns transaction requests with specified created_at upper limit.  Example: &#x60;/v1/transaction_requests?created_at_to&#x3D;2018-06-08&#x60;
  # @option opts [String] :amount_from Returns transaction requests with specified amount lower limit.  Example: &#x60;/v1/transaction_requests?currency&#x3D;BTC&amp;amount_from&#x3D;2.4319983&#x60;
  # @option opts [String] :amount_to Returns transaction requests with specified amount upper limit.  Example: &#x60;/v1/transaction_requests?currency&#x3D;BTC&amp;amount_to&#x3D;2.4319985&#x60;
  # @return [InlineResponse20016]
  describe 'get_transaction_requests test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_transaction_request
  # Creating a transaction request
  # Creates a new transaction request 
  # @param transaction_request 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2013]
  describe 'post_transaction_request test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
