=begin
#BitPesa API

#Reference documentation for the BitPesa API V1 ==============================================  Please also read the [API Onboarding](https://github.com/bitpesa/api-documentation) documentation that will give an overview on how the BitPesa API operates.  More specifically:  * [The onboarding process](https://github.com/bitpesa/api-documentation/blob/master/quick-integration.md) * [Authentication](https://github.com/bitpesa/api-documentation/blob/master/authentication.md) * [The transaction flow](https://github.com/bitpesa/api-documentation/blob/master/transaction-flow.md) * [Additional features](https://github.com/bitpesa/api-documentation/blob/master/additional-features.md)  Also see the [`Webhook`](#model-Webhook) description on how webhooks/callbacks are sent out from our system

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Bitpesa::CurrencyBase
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurrencyBase' do
  before do
    # run before each test
    @instance = Bitpesa::CurrencyBase.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrencyBase' do
    it 'should create an instance of CurrencyBase' do
      expect(@instance).to be_instance_of(Bitpesa::CurrencyBase)
    end
  end
  describe 'test attribute "code"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "symbol"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "decimals"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "subunit_to_unit"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "primary"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "min"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

