=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitPesa::InlineResponse4228Meta
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse4228Meta' do
  before do
    # run before each test
    @instance = BitPesa::InlineResponse4228Meta.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse4228Meta' do
    it 'should create an instance of InlineResponse4228Meta' do
      expect(@instance).to be_instance_of(BitPesa::InlineResponse4228Meta)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

