=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitPesa::Meta2
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Meta2' do
  before do
    # run before each test
    @instance = BitPesa::Meta2.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Meta2' do
    it 'should create an instance of Meta2' do
      expect(@instance).to be_instance_of(BitPesa::Meta2)
    end
  end
  describe 'test attribute "pagination"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

