=begin
#BitPesa API

#Reference documentation for the BitPesa API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Bitpesa::PayoutMethodDetailsXOFMobile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayoutMethodDetailsXOFMobile' do
  before do
    # run before each test
    @instance = Bitpesa::PayoutMethodDetailsXOFMobile.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayoutMethodDetailsXOFMobile' do
    it 'should create an instance of PayoutMethodDetailsXOFMobile' do
      expect(@instance).to be_instance_of(Bitpesa::PayoutMethodDetailsXOFMobile)
    end
  end
  describe 'test attribute "first_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "phone_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mobile_provider"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
