=begin
#BitPesa API

#Reference documentation for the BitPesa API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Bitpesa::RecipientState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecipientState' do
  before do
    # run before each test
    @instance = Bitpesa::RecipientState.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecipientState' do
    it 'should create an instance of RecipientState' do
      expect(@instance).to be_instance_of(Bitpesa::RecipientState)
    end
  end
end
