=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitPesa::Sender
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Sender' do
  before do
    # run before each test
    @instance = BitPesa::Sender.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Sender' do
    it 'should create an instance of Sender' do
      expect(@instance).to be_instance_of(BitPesa::Sender)
    end
  end
end

