=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitPesa::WebhookLogMetadataParams
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookLogMetadataParams' do
  before do
    # run before each test
    @instance = BitPesa::WebhookLogMetadataParams.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookLogMetadataParams' do
    it 'should create an instance of WebhookLogMetadataParams' do
      expect(@instance).to be_instance_of(BitPesa::WebhookLogMetadataParams)
    end
  end
  describe 'test attribute "webhook"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

