=begin
#BitPesa API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BitPesa::WebhookLogMetadataRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookLogMetadataRequest' do
  before do
    # run before each test
    @instance = BitPesa::WebhookLogMetadataRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookLogMetadataRequest' do
    it 'should create an instance of WebhookLogMetadataRequest' do
      expect(@instance).to be_instance_of(BitPesa::WebhookLogMetadataRequest)
    end
  end
  describe 'test attribute "headers"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "body"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

