=begin
#BitPesa API

#Reference documentation for the BitPesa API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

# Common files
require 'bitpesa-sdk/api_client'
require 'bitpesa-sdk/api_error'
require 'bitpesa-sdk/version'
require 'bitpesa-sdk/configuration'

# Models
require 'bitpesa-sdk/models/account'
require 'bitpesa-sdk/models/account_list_response'
require 'bitpesa-sdk/models/account_meta'
require 'bitpesa-sdk/models/account_response'
require 'bitpesa-sdk/models/account_validation_error'
require 'bitpesa-sdk/models/account_validation_request'
require 'bitpesa-sdk/models/account_validation_response'
require 'bitpesa-sdk/models/account_validation_result'
require 'bitpesa-sdk/models/api_log'
require 'bitpesa-sdk/models/api_log_list_response'
require 'bitpesa-sdk/models/api_log_response'
require 'bitpesa-sdk/models/currency'
require 'bitpesa-sdk/models/currency_exchange'
require 'bitpesa-sdk/models/currency_exchange_list_response'
require 'bitpesa-sdk/models/currency_list_response'
require 'bitpesa-sdk/models/currency_opposite'
require 'bitpesa-sdk/models/debit'
require 'bitpesa-sdk/models/debit_list_request'
require 'bitpesa-sdk/models/debit_list_response'
require 'bitpesa-sdk/models/debit_request'
require 'bitpesa-sdk/models/debit_request_wrapper'
require 'bitpesa-sdk/models/debit_response'
require 'bitpesa-sdk/models/document'
require 'bitpesa-sdk/models/document_list_response'
require 'bitpesa-sdk/models/document_request'
require 'bitpesa-sdk/models/document_response'
require 'bitpesa-sdk/models/document_webhook'
require 'bitpesa-sdk/models/error_status'
require 'bitpesa-sdk/models/field_description'
require 'bitpesa-sdk/models/field_select_validation'
require 'bitpesa-sdk/models/field_validation'
require 'bitpesa-sdk/models/pagination'
require 'bitpesa-sdk/models/pagination_meta'
require 'bitpesa-sdk/models/payin_method'
require 'bitpesa-sdk/models/payin_method_details'
require 'bitpesa-sdk/models/payin_method_details_mobile'
require 'bitpesa-sdk/models/payin_method_details_ngn_bank'
require 'bitpesa-sdk/models/payin_method_request'
require 'bitpesa-sdk/models/payment_method'
require 'bitpesa-sdk/models/payment_method_list_response'
require 'bitpesa-sdk/models/payment_method_opposite'
require 'bitpesa-sdk/models/payout_method'
require 'bitpesa-sdk/models/payout_method_bank_account_type_enum'
require 'bitpesa-sdk/models/payout_method_details'
require 'bitpesa-sdk/models/payout_method_details_balance'
require 'bitpesa-sdk/models/payout_method_details_ghs_bank'
require 'bitpesa-sdk/models/payout_method_details_iban'
require 'bitpesa-sdk/models/payout_method_details_mad_cash'
require 'bitpesa-sdk/models/payout_method_details_mobile'
require 'bitpesa-sdk/models/payout_method_details_ngn_bank'
require 'bitpesa-sdk/models/payout_method_details_xof_mobile'
require 'bitpesa-sdk/models/payout_method_gender_enum'
require 'bitpesa-sdk/models/payout_method_identity_card_type_enum'
require 'bitpesa-sdk/models/payout_method_list_response'
require 'bitpesa-sdk/models/payout_method_mobile_provider_enum'
require 'bitpesa-sdk/models/payout_method_request'
require 'bitpesa-sdk/models/payout_method_response'
require 'bitpesa-sdk/models/payout_method_webhook'
require 'bitpesa-sdk/models/recipient'
require 'bitpesa-sdk/models/recipient_list_response'
require 'bitpesa-sdk/models/recipient_request'
require 'bitpesa-sdk/models/recipient_response'
require 'bitpesa-sdk/models/recipient_state'
require 'bitpesa-sdk/models/recipient_webhook'
require 'bitpesa-sdk/models/sender'
require 'bitpesa-sdk/models/sender_list_response'
require 'bitpesa-sdk/models/sender_request'
require 'bitpesa-sdk/models/sender_response'
require 'bitpesa-sdk/models/sender_response_existing'
require 'bitpesa-sdk/models/sender_response_meta'
require 'bitpesa-sdk/models/sender_state'
require 'bitpesa-sdk/models/sender_webhook'
require 'bitpesa-sdk/models/transaction'
require 'bitpesa-sdk/models/transaction_list_response'
require 'bitpesa-sdk/models/transaction_request'
require 'bitpesa-sdk/models/transaction_response'
require 'bitpesa-sdk/models/transaction_response_existing'
require 'bitpesa-sdk/models/transaction_response_meta'
require 'bitpesa-sdk/models/transaction_state'
require 'bitpesa-sdk/models/transaction_traits'
require 'bitpesa-sdk/models/transaction_webhook'
require 'bitpesa-sdk/models/validation_error_description'
require 'bitpesa-sdk/models/webhook'
require 'bitpesa-sdk/models/webhook_definition'
require 'bitpesa-sdk/models/webhook_definition_event_list_response'
require 'bitpesa-sdk/models/webhook_definition_list_response'
require 'bitpesa-sdk/models/webhook_definition_request'
require 'bitpesa-sdk/models/webhook_definition_response'
require 'bitpesa-sdk/models/webhook_log'
require 'bitpesa-sdk/models/webhook_log_list_response'
require 'bitpesa-sdk/models/webhook_log_metadata'
require 'bitpesa-sdk/models/webhook_log_metadata_request'
require 'bitpesa-sdk/models/webhook_log_metadata_response'
require 'bitpesa-sdk/models/webhook_log_response'

# APIs
require 'bitpesa-sdk/api/api_logs_api'
require 'bitpesa-sdk/api/account_debits_api'
require 'bitpesa-sdk/api/account_validation_api'
require 'bitpesa-sdk/api/accounts_api'
require 'bitpesa-sdk/api/currency_info_api'
require 'bitpesa-sdk/api/documents_api'
require 'bitpesa-sdk/api/logs_api'
require 'bitpesa-sdk/api/payment_methods_api'
require 'bitpesa-sdk/api/payout_methods_api'
require 'bitpesa-sdk/api/recipients_api'
require 'bitpesa-sdk/api/senders_api'
require 'bitpesa-sdk/api/transactions_api'
require 'bitpesa-sdk/api/webhooks_api'

module Bitpesa
  class << self
    # Customize default settings for the SDK using block.
    #   Bitpesa.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
